from typing import Any

class NimPyException(Exception): ...

class enum_memory_regions:
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __get__(self, instance, owner) -> Any: ...
    def __iter__(self) -> Any: ...
    def __next__(self) -> Any: ...

class enum_modules:
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __get__(self, instance, owner) -> Any: ...
    def __iter__(self) -> Any: ...
    def __next__(self) -> Any: ...

class enum_processes:
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __get__(self, instance, owner) -> Any: ...
    def __iter__(self) -> Any: ...
    def __next__(self) -> Any: ...

class pixel_enum_region:
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __get__(self, instance, owner) -> Any: ...
    def __iter__(self) -> Any: ...
    def __next__(self) -> Any: ...

class pixel_enum_screen:
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __get__(self, instance, owner) -> Any: ...
    def __iter__(self) -> Any: ...
    def __next__(self) -> Any: ...

class pixel_search_colors:
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __get__(self, instance, owner) -> Any: ...
    def __iter__(self) -> Any: ...
    def __next__(self) -> Any: ...

def allocate_memory(*args, **kwargs) -> Any: ...
def aob_scan_bytes(*args, **kwargs) -> Any: ...
def aob_scan_module(*args, **kwargs) -> Any: ...
def aob_scan_range(*args, **kwargs) -> Any: ...
def begin_drawing(*args, **kwargs) -> Any: ...
def bytes_to_string(*args, **kwargs) -> Any: ...
def check_collision_circle_rec(*args, **kwargs) -> Any: ...
def check_collision_circles(*args, **kwargs) -> Any: ...
def check_collision_lines(*args, **kwargs) -> Any: ...
def check_collision_point_rec(*args, **kwargs) -> Any: ...
def check_collision_recs(*args, **kwargs) -> Any: ...
def close_process(*args, **kwargs) -> Any: ...
def compare_color_pct(*args, **kwargs) -> Any: ...
def draw_circle(*args, **kwargs) -> Any: ...
def draw_circle_lines(*args, **kwargs) -> Any: ...
def draw_circle_sector(*args, **kwargs) -> Any: ...
def draw_circle_sector_lines(*args, **kwargs) -> Any: ...
def draw_ellipse(*args, **kwargs) -> Any: ...
def draw_ellipse_lines(*args, **kwargs) -> Any: ...
def draw_font(*args, **kwargs) -> Any: ...
def draw_fps(*args, **kwargs) -> Any: ...
def draw_line(*args, **kwargs) -> Any: ...
def draw_pixel(*args, **kwargs) -> Any: ...
def draw_poly(*args, **kwargs) -> Any: ...
def draw_poly_lines(*args, **kwargs) -> Any: ...
def draw_rectangle(*args, **kwargs) -> Any: ...
def draw_rectangle_lines(*args, **kwargs) -> Any: ...
def draw_rectangle_rounded(*args, **kwargs) -> Any: ...
def draw_rectangle_rounded_lines(*args, **kwargs) -> Any: ...
def draw_ring(*args, **kwargs) -> Any: ...
def draw_ring_lines(*args, **kwargs) -> Any: ...
def draw_text(*args, **kwargs) -> Any: ...
def draw_texture(*args, **kwargs) -> Any: ...
def draw_triangle(*args, **kwargs) -> Any: ...
def draw_triangle_lines(*args, **kwargs) -> Any: ...
def end_drawing(*args, **kwargs) -> Any: ...
def fade_color(*args, **kwargs) -> Any: ...
def get_color(*args, **kwargs) -> Any: ...
def get_display_resolution(*args, **kwargs) -> Any: ...
def get_fps(*args, **kwargs) -> Any: ...
def get_module(*args, **kwargs) -> Any: ...
def get_monitor_count(*args, **kwargs) -> Any: ...
def get_monitor_name(*args, **kwargs) -> Any: ...
def get_monitor_refresh_rate(*args, **kwargs) -> Any: ...
def get_os_error(*args, **kwargs) -> Any: ...
def get_process_id(*args, **kwargs) -> Any: ...
def get_process_name(*args, **kwargs) -> Any: ...
def get_process_path(*args, **kwargs) -> Any: ...
def get_screen_height(*args, **kwargs) -> Any: ...
def get_screen_width(*args, **kwargs) -> Any: ...
def get_window_handle(*args, **kwargs) -> Any: ...
def get_window_info(*args, **kwargs) -> Any: ...
def get_window_position(*args, **kwargs) -> Any: ...
def get_window_title(*args, **kwargs) -> Any: ...
def gui_button(*args, **kwargs) -> Any: ...
def gui_check_box(*args, **kwargs) -> Any: ...
def gui_color_bar_alpha(*args, **kwargs) -> Any: ...
def gui_color_bar_hue(*args, **kwargs) -> Any: ...
def gui_color_picker(*args, **kwargs) -> Any: ...
def gui_combo_box(*args, **kwargs) -> Any: ...
def gui_dropdown_box(*args, **kwargs) -> Any: ...
def gui_fade(*args, **kwargs) -> Any: ...
def gui_group_box(*args, **kwargs) -> Any: ...
def gui_label(*args, **kwargs) -> Any: ...
def gui_label_button(*args, **kwargs) -> Any: ...
def gui_line(*args, **kwargs) -> Any: ...
def gui_load_style(*args, **kwargs) -> Any: ...
def gui_message_box(*args, **kwargs) -> Any: ...
def gui_panel(*args, **kwargs) -> Any: ...
def gui_progress_bar(*args, **kwargs) -> Any: ...
def gui_scroll_bar(*args, **kwargs) -> Any: ...
def gui_set_state(*args, **kwargs) -> Any: ...
def gui_slider(*args, **kwargs) -> Any: ...
def gui_slider_bar(*args, **kwargs) -> Any: ...
def gui_spinner(*args, **kwargs) -> Any: ...
def gui_status_bar(*args, **kwargs) -> Any: ...
def gui_text_box(*args, **kwargs) -> Any: ...
def gui_window_box(*args, **kwargs) -> Any: ...
def is_64_bit(*args, **kwargs) -> Any: ...
def is_sound_playing(*args, **kwargs) -> Any: ...
def key_pressed(*args, **kwargs) -> Any: ...
def load_font(*args, **kwargs) -> Any: ...
def load_sound(*args, **kwargs) -> Any: ...
def load_texture(*args, **kwargs) -> Any: ...
def load_texture_bytes(*args, **kwargs) -> Any: ...
def measure_font(*args, **kwargs) -> Any: ...
def measure_text(*args, **kwargs) -> Any: ...
def mouse_click(*args, **kwargs) -> Any: ...
def mouse_down(*args, **kwargs) -> Any: ...
def mouse_move(*args, **kwargs) -> Any: ...
def mouse_position(*args, **kwargs) -> Any: ...
def mouse_up(*args, **kwargs) -> Any: ...
def new_color(*args, **kwargs) -> Any: ...
def new_color_hex(*args, **kwargs) -> Any: ...
def open_process(*args, **kwargs) -> Any: ...
def overlay_close(*args, **kwargs) -> Any: ...
def overlay_init(*args, **kwargs) -> Any: ...
def overlay_loop(*args, **kwargs) -> Any: ...
def page_protection(*args, **kwargs) -> Any: ...
def pause_sound(*args, **kwargs) -> Any: ...
def pid_exists(*args, **kwargs) -> Any: ...
def pixel_at_mouse(*args, **kwargs) -> Any: ...
def pixel_save_to_file(*args, **kwargs) -> Any: ...
def play_multisound(*args, **kwargs) -> Any: ...
def play_sound(*args, **kwargs) -> Any: ...
def pointer_chain(*args, **kwargs) -> Any: ...
def pointer_chain_32(*args, **kwargs) -> Any: ...
def pointer_chain_64(*args, **kwargs) -> Any: ...
def press_key(*args, **kwargs) -> Any: ...
def process_exists(*args, **kwargs) -> Any: ...
def process_running(*args, **kwargs) -> Any: ...
def r(*args, **kwargs) -> Any: ...
def r_bool(*args, **kwargs) -> Any: ...
def r_byte(*args, **kwargs) -> Any: ...
def r_bytes(*args, **kwargs) -> Any: ...
def r_ctype(*args, **kwargs) -> Any: ...
def r_float(*args, **kwargs) -> Any: ...
def r_float64(*args, **kwargs) -> Any: ...
def r_floats(*args, **kwargs) -> Any: ...
def r_floats64(*args, **kwargs) -> Any: ...
def r_int(*args, **kwargs) -> Any: ...
def r_int16(*args, **kwargs) -> Any: ...
def r_int64(*args, **kwargs) -> Any: ...
def r_ints(*args, **kwargs) -> Any: ...
def r_ints16(*args, **kwargs) -> Any: ...
def r_ints64(*args, **kwargs) -> Any: ...
def r_string(*args, **kwargs) -> Any: ...
def r_uint(*args, **kwargs) -> Any: ...
def r_uint64(*args, **kwargs) -> Any: ...
def r_uints(*args, **kwargs) -> Any: ...
def r_uints64(*args, **kwargs) -> Any: ...
def r_vec2(*args, **kwargs) -> Any: ...
def r_vec3(*args, **kwargs) -> Any: ...
def resume_sound(*args, **kwargs) -> Any: ...
def run_time(*args, **kwargs) -> Any: ...
def set_fps(*args, **kwargs) -> Any: ...
def set_sound_volume(*args, **kwargs) -> Any: ...
def set_window_flag(*args, **kwargs) -> Any: ...
def set_window_icon(*args, **kwargs) -> Any: ...
def set_window_position(*args, **kwargs) -> Any: ...
def set_window_size(*args, **kwargs) -> Any: ...
def set_window_title(*args, **kwargs) -> Any: ...
def sound_deinit(*args, **kwargs) -> Any: ...
def sound_init(*args, **kwargs) -> Any: ...
def stop_multisound(*args, **kwargs) -> Any: ...
def stop_sound(*args, **kwargs) -> Any: ...
def take_screenshot(*args, **kwargs) -> Any: ...
def toggle_mouse(*args, **kwargs) -> Any: ...
def unload_sound(*args, **kwargs) -> Any: ...
def unload_texture(*args, **kwargs) -> Any: ...
def vec2(*args, **kwargs) -> Any: ...
def vec2_add(*args, **kwargs) -> Any: ...
def vec2_add_value(*args, **kwargs) -> Any: ...
def vec2_closest(*args, **kwargs) -> Any: ...
def vec2_distance(*args, **kwargs) -> Any: ...
def vec2_divide(*args, **kwargs) -> Any: ...
def vec2_length(*args, **kwargs) -> Any: ...
def vec2_length_sqr(*args, **kwargs) -> Any: ...
def vec2_multiply(*args, **kwargs) -> Any: ...
def vec2_multiply_value(*args, **kwargs) -> Any: ...
def vec2_subtract(*args, **kwargs) -> Any: ...
def vec2_subtract_value(*args, **kwargs) -> Any: ...
def vec3(*args, **kwargs) -> Any: ...
def vec3_add(*args, **kwargs) -> Any: ...
def vec3_add_value(*args, **kwargs) -> Any: ...
def vec3_closest(*args, **kwargs) -> Any: ...
def vec3_distance(*args, **kwargs) -> Any: ...
def vec3_divide(*args, **kwargs) -> Any: ...
def vec3_length(*args, **kwargs) -> Any: ...
def vec3_length_sqr(*args, **kwargs) -> Any: ...
def vec3_multiply(*args, **kwargs) -> Any: ...
def vec3_multiply_value(*args, **kwargs) -> Any: ...
def vec3_subtract(*args, **kwargs) -> Any: ...
def vec3_subtract_value(*args, **kwargs) -> Any: ...
def w(*args, **kwargs) -> Any: ...
def w_bool(*args, **kwargs) -> Any: ...
def w_byte(*args, **kwargs) -> Any: ...
def w_bytes(*args, **kwargs) -> Any: ...
def w_ctype(*args, **kwargs) -> Any: ...
def w_float(*args, **kwargs) -> Any: ...
def w_float64(*args, **kwargs) -> Any: ...
def w_floats(*args, **kwargs) -> Any: ...
def w_floats64(*args, **kwargs) -> Any: ...
def w_int(*args, **kwargs) -> Any: ...
def w_int16(*args, **kwargs) -> Any: ...
def w_int64(*args, **kwargs) -> Any: ...
def w_ints(*args, **kwargs) -> Any: ...
def w_ints16(*args, **kwargs) -> Any: ...
def w_ints64(*args, **kwargs) -> Any: ...
def w_string(*args, **kwargs) -> Any: ...
def w_uint(*args, **kwargs) -> Any: ...
def w_uint64(*args, **kwargs) -> Any: ...
def w_uints(*args, **kwargs) -> Any: ...
def w_uints64(*args, **kwargs) -> Any: ...
def w_vec2(*args, **kwargs) -> Any: ...
def w_vec3(*args, **kwargs) -> Any: ...
def world_to_screen(*args, **kwargs) -> Any: ...
