[Act1]
RogueEncampment = true
BloodMoor = true
ColdPlains = true
StonyFields = true
DarkWood = true
BlackMarsh = true
TamoeHighland = true
DenOfEvil = true
CaveLevel1 = true
UndergroundPassageLevel1 = true
HoleLevel1 = true
PitLevel1 = true
CaveLevel2 = true
UndergroundPassageLevel2 = true
HoleLevel2 = true
PitLevel2 = true
BurialGrounds = true
Crypt = true
Mausoleum = true
ForgottenTower = true
TowerCellarLevel1 = true
TowerCellarLevel2 = true
TowerCellarLevel3 = true
TowerCellarLevel4 = true
TowerCellarLevel5 = true
MonasteryGate = true
OuterCloister = true
Barracks = true
JailLevel1 = true
JailLevel2 = true
JailLevel3 = true
InnerCloister = true
Cathedral = true
CatacombsLevel1 = true
CatacombsLevel2 = true
CatacombsLevel3 = true
CatacombsLevel4 = true
Tristram = true
MooMooFarm = true

[Act2]
LutGholein = true
RockyWaste = true
DryHills = true
FarOasis = true
LostCity = true
ValleyOfSnakes = true
CanyonOfTheMagi = true
SewersLevel1Act2 = true
SewersLevel2Act2 = true
SewersLevel3Act2 = true
HaremLevel1 = true
HaremLevel2 = true
PalaceCellarLevel1 = true
PalaceCellarLevel2 = true
PalaceCellarLevel3 = true
StonyTombLevel1 = true
HallsOfTheDeadLevel1 = true
HallsOfTheDeadLevel2 = true
ClawViperTempleLevel1 = true
StonyTombLevel2 = true
HallsOfTheDeadLevel3 = true
ClawViperTempleLevel2 = true
MaggotLairLevel1 = true
MaggotLairLevel2 = true
MaggotLairLevel3 = true
AncientTunnels = true
TalRashasTomb1 = true
TalRashasTomb2 = true
TalRashasTomb3 = true
TalRashasTomb4 = true
TalRashasTomb5 = true
TalRashasTomb6 = true
TalRashasTomb7 = true
DurielsLair = true
ArcaneSanctuary = true

[Act3]
KurastDocks = true
SpiderForest = true
GreatMarsh = true
FlayerJungle = true
LowerKurast = true
KurastBazaar = true
UpperKurast = true
KurastCauseway = true
Travincal = true
SpiderCave = true
SpiderCavern = true
SwampyPitLevel1 = true
SwampyPitLevel2 = true
FlayerDungeonLevel1 = true
FlayerDungeonLevel2 = true
SwampyPitLevel3 = true
FlayerDungeonLevel3 = true
SewersLevel1Act3 = true
SewersLevel2Act3 = true
RuinedTemple = true
DisusedFane = true
ForgottenReliquary = true
ForgottenTemple = true
RuinedFane = true
DisusedReliquary = true
DuranceOfHateLevel1 = true
DuranceOfHateLevel2 = true
DuranceOfHateLevel3 = true

[Act4]
ThePandemoniumFortress = true
OuterSteppes = true
PlainsOfDespair = true
CityOfTheDamned = true
RiverOfFlame = true
ChaosSanctuary = true

[Act5]
Harrogath = true
BloodyFoothills = true
FrigidHighlands = true
ArreatPlateau = true
FrozenRiver = true
FrozenTundra = true
DrifterCavern = true
CrystallinePassage = true
GlacialTrail = true
TheAncientsWay = true
ArreatSummit = true
IcyCellar = true
NihlathaksTemple = true
HallsOfAnguish = true
HallsOfPain = true
HallsOfVaught = true
Abaddon = true
PitOfAcheron = true
InfernalPit = true
TheWorldStoneKeepLevel1 = true
TheWorldStoneKeepLevel2 = true
TheWorldStoneKeepLevel3 = true
ThroneOfDestruction = true
TheWorldstoneChamber = true
